name: whatsapp_clone
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  simple_animations: ^5.0.2
  firebase_core: ^3.8.1
  firebase_ui_firestore: ^1.7.0 
  firebase_ui_firestore_slivers: ^3.0.0
  firebase_storage: ^12.3.7
  google_sign_in: ^6.2.2
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  firebase_auth: ^5.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logo/

  #-FONTS
  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/AlbertSans/AlbertSans-Regular.ttf
        - asset: assets/fonts/AlbertSans/AlbertSans-Light.ttf
          weight: 100
        - asset: assets/fonts/AlbertSans/AlbertSans-Medium.ttf
          weight: 200
        - asset: assets/fonts/AlbertSans/AlbertSans-MediumItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/AlbertSans/AlbertSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/AlbertSans/AlbertSans-SemiBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-Italic.ttf
          style: italic